/* initial data setup for H2 */

DELETE FROM USER;
DELETE FROM ROLE_PERMISSIONS;
DELETE FROM ROLE;

// create roles
INSERT INTO ROLE (ID, CREATED_AT, UPDATED_AT, NAME) VALUES (1, now(), now(), 'guest');
INSERT INTO ROLE (ID, CREATED_AT, UPDATED_AT, NAME) VALUES (2, now(), now(), 'admin');

// create role permissions
INSERT INTO ROLE_PERMISSIONS (ROLE, PERMISSIONS) VALUES (2, 'EDIT_USER');
INSERT INTO ROLE_PERMISSIONS (ROLE, PERMISSIONS) VALUES (2, 'CREATE_USER');
INSERT INTO ROLE_PERMISSIONS (ROLE, PERMISSIONS) VALUES (2, 'DELETE_USER');
INSERT INTO ROLE_PERMISSIONS (ROLE, PERMISSIONS) VALUES (2, 'SHOW_USER');
// TODO do

// create admin user
INSERT INTO USER (ID, CREATED_AT, UPDATED_AT, ACTIVATED, EMAIL, FULL_NAME, PASSWORD, USERNAME, ROLE)
  VALUES (1 , NOW(), NOW(), TRUE, 'admin@iaahausarbeit.de', 'Administrator', '$2a$10$.p3HZN.0FySMsam8Yz7er.2NlbBzQPXQYUCt.karL3F6ycXSvAaBy', 'admin', 2);